package setup

import (
	"bufio"
	"fmt"
	"io"
	"os"
	"strings"
)

// Runner handles the interactive setup wizard.
type Runner struct {
	In  io.Reader
	Out io.Writer
}

// New creates a setup runner using stdin/stdout.
func New() *Runner {
	return &Runner{In: os.Stdin, Out: os.Stdout}
}

// Run walks the user through interactive configuration and writes a .env file.
func (r *Runner) Run() error {
	scanner := bufio.NewScanner(r.In)
	env := map[string]string{}

	r.print("\n========================================")
	r.print("  Sidekick — Interactive Setup Wizard")
	r.print("========================================\n")

	// --- Phase 1: Core (always asked) ---
	r.print("[Core Settings]\n")

	env["SIDEKICK_PORT"] = r.ask(scanner, "Port for Sidekick to listen on", "8081")
	env["SIDEKICK_UPSTREAM_URL"] = r.ask(scanner, "Upstream service URL", "http://localhost:8080")
	env["SIDEKICK_RATE_LIMIT_RATE"] = r.ask(scanner, "Rate limit (requests/sec per IP)", "10")
	env["SIDEKICK_RATE_LIMIT_BURST"] = r.ask(scanner, "Rate limit burst size", "20")

	// --- Phase 2: JWT Auth ---
	r.print("\n[JWT Authentication] (optional — skip to disable)\n")

	if r.askYesNo(scanner, "Enable JWT authentication?", false) {
		env["SIDEKICK_JWT_SECRET"] = r.ask(scanner, "JWT secret key (HMAC-SHA256)", "")
		pubKeyPath := r.ask(scanner, "RSA public key file path (leave empty for HMAC only)", "")
		if pubKeyPath != "" {
			env["SIDEKICK_JWT_PUBLIC_KEY"] = pubKeyPath
		}
		issuer := r.ask(scanner, "Expected token issuer (leave empty to skip)", "")
		if issuer != "" {
			env["SIDEKICK_JWT_ISSUER"] = issuer
		}
	}

	// --- Phase 2: Redis ---
	r.print("\n[Distributed Rate Limiting] (optional — skip to use in-memory)\n")

	if r.askYesNo(scanner, "Enable Redis for distributed rate limiting?", false) {
		env["SIDEKICK_REDIS_URL"] = r.ask(scanner, "Redis URL", "redis://localhost:6379")
		env["SIDEKICK_REDIS_DB"] = r.ask(scanner, "Redis database number", "0")
	}

	// --- Phase 2: SQLite Config ---
	r.print("\n[Dynamic Configuration] (optional — skip to use env vars only)\n")

	if r.askYesNo(scanner, "Enable SQLite config database for hot reload?", false) {
		env["SIDEKICK_CONFIG_DB"] = r.ask(scanner, "SQLite database file path", "./sidekick.db")
		env["SIDEKICK_CONFIG_RELOAD_INTERVAL"] = r.ask(scanner, "Config reload interval (seconds)", "30")
	}

	// --- Phase 2: Request Capture ---
	r.print("\n[Request Capture] (optional — for debugging)\n")

	if r.askYesNo(scanner, "Enable request/response body capture?", false) {
		env["SIDEKICK_CAPTURE_BODIES"] = "true"
		env["SIDEKICK_LOG_BUFFER_SIZE"] = r.ask(scanner, "Request log buffer size", "100")
	}

	// --- Write .env file ---
	r.print("\n----------------------------------------")
	return r.writeEnvFile(env)
}

func (r *Runner) print(msg string) {
	fmt.Fprintln(r.Out, msg)
}

func (r *Runner) ask(scanner *bufio.Scanner, prompt string, defaultVal string) string {
	if defaultVal != "" {
		fmt.Fprintf(r.Out, "  %s [%s]: ", prompt, defaultVal)
	} else {
		fmt.Fprintf(r.Out, "  %s: ", prompt)
	}

	if scanner.Scan() {
		input := strings.TrimSpace(scanner.Text())
		if input != "" {
			return input
		}
	}
	return defaultVal
}

func (r *Runner) askYesNo(scanner *bufio.Scanner, prompt string, defaultYes bool) bool {
	hint := "y/N"
	if defaultYes {
		hint = "Y/n"
	}
	fmt.Fprintf(r.Out, "  %s (%s): ", prompt, hint)

	if scanner.Scan() {
		input := strings.TrimSpace(strings.ToLower(scanner.Text()))
		if input == "y" || input == "yes" {
			return true
		}
		if input == "n" || input == "no" {
			return false
		}
	}
	return defaultYes
}

func (r *Runner) writeEnvFile(env map[string]string) error {
	// Ordered keys for a clean .env file
	order := []string{
		"SIDEKICK_PORT",
		"SIDEKICK_UPSTREAM_URL",
		"SIDEKICK_RATE_LIMIT_RATE",
		"SIDEKICK_RATE_LIMIT_BURST",
		"SIDEKICK_JWT_SECRET",
		"SIDEKICK_JWT_PUBLIC_KEY",
		"SIDEKICK_JWT_ISSUER",
		"SIDEKICK_REDIS_URL",
		"SIDEKICK_REDIS_DB",
		"SIDEKICK_CONFIG_DB",
		"SIDEKICK_CONFIG_RELOAD_INTERVAL",
		"SIDEKICK_CAPTURE_BODIES",
		"SIDEKICK_LOG_BUFFER_SIZE",
	}

	var lines []string
	lines = append(lines, "# Sidekick Configuration")
	lines = append(lines, "# Generated by: sidekick setup")
	lines = append(lines, "")

	section := ""
	for _, key := range order {
		val, ok := env[key]
		if !ok || val == "" {
			continue
		}

		// Add section headers
		newSection := sectionFor(key)
		if newSection != section {
			if section != "" {
				lines = append(lines, "")
			}
			lines = append(lines, "# "+newSection)
			section = newSection
		}

		lines = append(lines, fmt.Sprintf("%s=%s", key, val))
	}
	lines = append(lines, "")

	content := strings.Join(lines, "\n")

	if err := os.WriteFile(".env", []byte(content), 0644); err != nil {
		return fmt.Errorf("failed to write .env file: %w", err)
	}

	r.print("Config saved to .env")
	r.print("\nRun 'sidekick' to start with this configuration.")
	r.print("Run 'sidekick setup' again to reconfigure.\n")
	return nil
}

func sectionFor(key string) string {
	switch {
	case strings.HasPrefix(key, "SIDEKICK_JWT") || key == "SIDEKICK_AUTH_ENABLED":
		return "JWT Authentication"
	case strings.HasPrefix(key, "SIDEKICK_REDIS"):
		return "Distributed Rate Limiting (Redis)"
	case strings.HasPrefix(key, "SIDEKICK_CONFIG"):
		return "Dynamic Configuration (SQLite)"
	case strings.HasPrefix(key, "SIDEKICK_CAPTURE") || key == "SIDEKICK_LOG_BUFFER_SIZE":
		return "Request Capture"
	default:
		return "Core"
	}
}
